name: stocktok
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure compatibility with Dart 3

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  http: ^1.3.0
  marquee: ^2.3.0
  shared_preferences: ^2.4.0
  fl_chart: ^0.70.2
  cloud_firestore: ^5.6.2
  overlay_support: ^2.1.0
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for recommended coding practices
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Asset and font configuration
  assets:
    - assets/fonts/
    - assets/images/
    - .env
    - assets/logos/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Condensed-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_SemiCondensed-Bold.ttf
          weight: 600
