// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5pIpniKNugvuxoAIqZAfkgrltWObdVlw',
    appId: '1:45009812067:android:36109fa5bc307f853d1656',
    messagingSenderId: '45009812067',
    projectId: 'stock-tok',
    storageBucket: 'stock-tok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2a2RIcWka4FyO_GTGuL2LU4Z0c-XlaiE',
    appId: '1:45009812067:ios:00339538aa8a5a613d1656',
    messagingSenderId: '45009812067',
    projectId: 'stock-tok',
    storageBucket: 'stock-tok.firebasestorage.app',
    iosBundleId: 'com.example.stocktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2a2RIcWka4FyO_GTGuL2LU4Z0c-XlaiE',
    appId: '1:45009812067:ios:00339538aa8a5a613d1656',
    messagingSenderId: '45009812067',
    projectId: 'stock-tok',
    storageBucket: 'stock-tok.firebasestorage.app',
    iosBundleId: 'com.example.stocktok',
  );

}